@startuml
[*] -> AA
AA : 0
AC : 4
BO : 18
CD : 25
DI : 13
DT : 24
DY : 23
ID : 11
KL : 21
KW : 6
MJ : 3
OI : 10
OU : 8
RH : 15
TO : 19
YS : 22
AA --> AC : 2
AA --> BO : 5
AA --> CD : 5
AA --> DI : 4
AA --> DT : 7
AA --> DY : 6
AA --> ID : 4
AA --> KL : 4
AA --> KW : 3
AA --> MJ : 2
AA --> OI : 2
AA --> OU : 2
AA --> RH : 5
AA --> TO : 4
AA --> YS : 6
AC --> BO : 6
AC --> CD : 5
AC --> DI : 6
AC --> DT : 5
AC --> DY : 8
AC --> ID : 5
AC --> KL : 2
AC --> KW : 3
AC --> MJ : 3
AC --> OI : 3
AC --> OU : 4
AC --> RH : 7
AC --> TO : 6
AC --> YS : 6
BO --> CD : 7
BO --> DI : 9
BO --> DT : 11
BO --> DY : 11
BO --> ID : 3
BO --> KL : 8
BO --> KW : 5
BO --> MJ : 3
BO --> OI : 3
BO --> OU : 7
BO --> RH : 10
BO --> TO : 9
BO --> YS : 8
CD --> DI : 9
CD --> DT : 10
CD --> DY : 11
CD --> ID : 9
CD --> KL : 7
CD --> KW : 2
CD --> MJ : 4
CD --> OI : 7
CD --> OU : 7
CD --> RH : 10
CD --> TO : 9
CD --> YS : 3
DI --> DT : 11
DI --> DY : 2
DI --> ID : 8
DI --> KL : 8
DI --> KW : 7
DI --> MJ : 6
DI --> OI : 6
DI --> OU : 2
DI --> RH : 2
DI --> TO : 3
DI --> YS : 10
DT --> DY : 13
DT --> ID : 10
DT --> KL : 3
DT --> KW : 8
DT --> MJ : 8
DT --> OI : 8
DT --> OU : 9
DT --> RH : 12
DT --> TO : 11
DT --> YS : 11
DY --> ID : 10
DY --> KL : 10
DY --> KW : 9
DY --> MJ : 8
DY --> OI : 8
DY --> OU : 4
DY --> RH : 4
DY --> TO : 3
DY --> YS : 12
ID --> KL : 7
ID --> KW : 7
ID --> MJ : 5
ID --> OI : 2
ID --> OU : 6
ID --> RH : 9
ID --> TO : 8
ID --> YS : 10
KL --> KW : 5
KL --> MJ : 5
KL --> OI : 5
KL --> OU : 6
KL --> RH : 9
KL --> TO : 8
KL --> YS : 8
KW --> MJ : 2
KW --> OI : 5
KW --> OU : 5
KW --> RH : 8
KW --> TO : 7
KW --> YS : 3
MJ --> OI : 3
MJ --> OU : 4
MJ --> RH : 7
MJ --> TO : 6
MJ --> YS : 5
OI --> OU : 4
OI --> RH : 7
OI --> TO : 6
OI --> YS : 8
OU --> RH : 3
OU --> TO : 2
OU --> YS : 8
RH --> TO : 3
RH --> YS : 11
TO --> YS : 10
@enduml